config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      sessions: 'authentication/sessions'
  }

  get 'rooms/show'

  scope "(:locale)", locale: /en|vi/ do
    resources :people
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :line_items
    resources :carts, except: [:index, :edit]
    resources :products
    resources :posts
    resources :users
    resources :categories, only: [:index, :show]

    namespace :manager do
      resources :categories
    end
    get 'display' => 'home#post_display'
    post 'add_fav' => 'posts#add_favorite'
    #checkout cart
    get 'checkout' => 'checkouts#checkout'
    post 'confirm' => 'checkouts#confirm'
    #signin & sign up
    controller :sessions do
      get 'login' => :index
      post 'login' => :create
      delete 'logout' => :destroy
    end

    root "home#index"
  end
  resources :comments, only: [:create, :index, :destroy]

  get 'budgets' => 'budgets#download'
  mount ActionCable.server => '/cable'

  get 'room' => 'rooms#show'
  # get '*path', to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, :dependent => :destroy

  def add_product product_id
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(:product_id => product_id)
    end
    current_item
  end
  def total_price
    line_items.to_a.sum { |item| item.total_price}
  end
end

app/models/category.rb
class Category < ApplicationRecord
  self.primary_key = 'cat_id'
  has_many :products, :dependent => :destroy

  validates :cat_id, :cat_name, :cat_content, :presence => true
  validates :cat_name, :cat_id,  :uniqueness => true

  def self.get_category
    select('cat_id, cat_name, cat_content').order('cat_name asc')
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :body, presence: true, allow_blank: false
end

app/models/interaction.rb
class Interaction < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total_price
    product.price * quantity
  end
end

app/models/message.rb
class Message < ApplicationRecord
  after_create_commit { BroadcastMessageJob.perform_later self }
  belongs_to :user
end

app/models/person.rb
class Person < ApplicationRecord

  belongs_to :user, foreign_key: :user_id
  def address
    Address.new(city, state)
  end

  def address=(address)
    self[:city] = address.city
    self[:state] = address.state
    @address = address
  end
end
class Address
  attr_reader :city, :state

  def initialize(city, state)
    @city, @state = city, state
  end

  def ==(other_address)
    city == other_address.city && state == other_address.state
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :interactions, :dependent => :destroy
  has_many :users, through: :interactions
  has_many :comments, dependent: :destroy

  validates :title, :uniqueness => true
  validates :title, :content, :presence => true
end

app/models/product.rb
class Product < ApplicationRecord
  # self.default_scope :order => 'title'

  has_many :line_items
  belongs_to :category, foreign_key: :category_id
  before_destroy :line_item_referencing_product
  mount_uploader :image_url, ImageUploader

  private
    def line_item_referencing_product
      if line_items.empty?
        true
      else
        errors.add(:base, 'line items present')
        false
      end
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default authentication modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :person, dependent: :destroy
  has_many :interactions, :dependent => :destroy
  has_many :posts, through: :interactions
  has_many :comments, dependent: :destroy

  # validates :name, :presence => true, :uniqueness => true
  # validates :password, :confirmation => true
  # validate :password_must_be_present
  #
  # attr_accessor :password_confirmation
  # attr_reader   :password

  # def User.encrypt_password(password, salt)
  #   Digest::SHA2.hexdigest(password + "wibble" + salt)
  # end
  #
  # def password=(password)
  #   @password = password
  #
  #   if password.present?
  #     generate_salt
  #     self.hashed_password = self.class.encrypt_password(password, salt)
  #   end
  # end
  #
  # def User.authenticate(name, password)
  #   if user = find_by_name(name)
  #     if user.hashed_password == encrypt_password(password,user.salt)
  #       user
  #     end
  #   end
  # end
  #
  # private
  #   def password_must_be_present
  #     errors.add(:password, "missing password") unless hashed_password.present?
  #   end
  #
  #   def generate_salt
  #     self.salt = self.object_id.to_s + rand.to_s
  #   end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Your cart is empty' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      # @cart = Cart.find(params[:id])
      begin
        @cart=Cart.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        logger.error "Attempt to access invalid cart #{params[:id]}"
        redirect_to root_path, :notice => "Invalid cart"
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def number_to_currency price
    sprintf("$%0.02f", price)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user] = user
  end

  def log_out
    session.delete :user
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/_form.html.slim
= form_for(cart) do |f|
  - if cart.errors.any?
    #error_explanation
      h2
        = pluralize(cart.errors.count, "error")
        |  prohibited this cart from being saved:
      ul
        - cart.errors.full_messages.each do |message|
          li
            = message
  .actions
    = f.submit

app/views/carts/checkout.html.slim
- content_for :title do
  |   Confirm Cart

h1
  | Cart information

= render 'partials/messages'
table.table.table-striped.table-bordered.table-hover
  thead
    tr
      th
        | No.
      th
        | Title
      th
        | Quantity
      th
        | Price
      th
        | Total
      th
  tbody
    - @cart.line_items.each do |line_item|
      tr
        td
        td
          = line_item.product.title
        td
          = line_item.quantity
        td
          = line_item.product.price
        td
          = number_to_currency(line_item.total_price)
        td
    tr
      td[colspan="4"]
        | Total
      td
        = number_to_currency(@cart.total_price)

= button_to 'Back to cart', checkout_path, method: 'get'
= button_to 'Confirm', checkout_path, method: 'get', confirm: 'Are you sure?'

app/views/carts/edit.html.slim
h1
  | Editing Cart
= render 'form', cart: @cart
= link_to 'Show', @cart
|  | 
= link_to 'Back', carts_path

app/views/carts/index.html.slim
p#notice
  = notice
h1
  | Carts
table
  thead
    tr
      th[colspan="3"]
  tbody
    - @carts.each do |cart|
      tr
        td
          = link_to 'Show', cart
        td
          = link_to 'Edit', edit_cart_path(cart)
        td
          = link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New Cart', new_cart_path

app/views/carts/new.html.slim
h1
  | New Cart
= render 'form', cart: @cart
= link_to 'Back', carts_path

app/views/carts/show.html.slim
- content_for :title do
  |   Your Cart

h1
  | Cart information
= render 'partials/messages'
table.table.table-striped.table-bordered.table-hover
  thead
    tr
      th
        | No.
      th
        | Title
      th
        | Quantity
      th
        | Price
      th
        | Total
      th
  tbody
    = render @cart.line_items
    tr
      td[colspan="4"]
        | Total
      td
        = number_to_currency(@cart.total_price)
      td
        = button_to 'Empty cart', @cart, method: 'delete', confirm: 'Are you sure?'

= button_to 'Buy continue', @cart, method: 'get'
= button_to 'Checkout', checkout_path, method: 'get', confirm: 'Are you sure?'