config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      sessions: 'authentication/sessions'
  }

  get 'rooms/show'

  scope "(:locale)", locale: /en|vi/ do
    resources :people
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :line_items
    resources :carts, except: [:index, :edit]
    resources :products
    resources :posts
    resources :users
    resources :categories, only: [:index, :show]

    namespace :manager do
      resources :categories
    end
    get 'display' => 'home#post_display'
    post 'add_fav' => 'posts#add_favorite'
    #checkout cart
    get 'checkout' => 'checkouts#checkout'
    post 'confirm' => 'checkouts#confirm'
    #signin & sign up
    controller :sessions do
      get 'login' => :index
      post 'login' => :create
      delete 'logout' => :destroy
    end

    root "home#index"
  end
  resources :comments, only: [:create, :index, :destroy]

  get 'budgets' => 'budgets#download'
  mount ActionCable.server => '/cable'

  get 'room' => 'rooms#show'
  # get '*path', to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, :dependent => :destroy

  def add_product product_id
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(:product_id => product_id)
    end
    current_item
  end
  def total_price
    line_items.to_a.sum { |item| item.total_price}
  end
end

app/models/category.rb
class Category < ApplicationRecord
  self.primary_key = 'cat_id'
  has_many :products, :dependent => :destroy

  validates :cat_id, :cat_name, :cat_content, :presence => true
  validates :cat_name, :cat_id,  :uniqueness => true

  def self.get_category
    select('cat_id, cat_name, cat_content').order('cat_name asc')
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :body, presence: true, allow_blank: false
end

app/models/interaction.rb
class Interaction < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total_price
    product.price * quantity
  end
end

app/models/message.rb
class Message < ApplicationRecord
  after_create_commit { BroadcastMessageJob.perform_later self }
  belongs_to :user
end

app/models/person.rb
class Person < ApplicationRecord

  belongs_to :user, foreign_key: :user_id
  def address
    Address.new(city, state)
  end

  def address=(address)
    self[:city] = address.city
    self[:state] = address.state
    @address = address
  end
end
class Address
  attr_reader :city, :state

  def initialize(city, state)
    @city, @state = city, state
  end

  def ==(other_address)
    city == other_address.city && state == other_address.state
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :interactions, :dependent => :destroy
  has_many :users, through: :interactions
  has_many :comments, dependent: :destroy

  validates :title, :uniqueness => true
  validates :title, :content, :presence => true
end

app/models/product.rb
class Product < ApplicationRecord
  # self.default_scope :order => 'title'

  has_many :line_items
  belongs_to :category, foreign_key: :category_id
  before_destroy :line_item_referencing_product
  mount_uploader :image_url, ImageUploader

  private
    def line_item_referencing_product
      if line_items.empty?
        true
      else
        errors.add(:base, 'line items present')
        false
      end
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default authentication modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :person, dependent: :destroy
  has_many :interactions, :dependent => :destroy
  has_many :posts, through: :interactions
  has_many :comments, dependent: :destroy

  # validates :name, :presence => true, :uniqueness => true
  # validates :password, :confirmation => true
  # validate :password_must_be_present
  #
  # attr_accessor :password_confirmation
  # attr_reader   :password

  # def User.encrypt_password(password, salt)
  #   Digest::SHA2.hexdigest(password + "wibble" + salt)
  # end
  #
  # def password=(password)
  #   @password = password
  #
  #   if password.present?
  #     generate_salt
  #     self.hashed_password = self.class.encrypt_password(password, salt)
  #   end
  # end
  #
  # def User.authenticate(name, password)
  #   if user = find_by_name(name)
  #     if user.hashed_password == encrypt_password(password,user.salt)
  #       user
  #     end
  #   end
  # end
  #
  # private
  #   def password_must_be_present
  #     errors.add(:password, "missing password") unless hashed_password.present?
  #   end
  #
  #   def generate_salt
  #     self.salt = self.object_id.to_s + rand.to_s
  #   end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authorize
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @post  = Post.new
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    respond_to do |format|
      format.js {render "posts/update"}
    end
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.interactions.build(post_id: @post.id, user_id: session[:user]['id'], like: 0, share: 0, comment: 0)

    respond_to do |format|
      if @post.save
        format.js
        flash[:notice] = "Post, which Id is #{@post.id} was successfully created."
      else
        format.js
        @post.errors.each do |key, value|
        end
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.jsonpo
  def update
    respond_to do |format|po
      if @post.update(post_params)
        format.js { @post }
        flash[:notice] = "Post, which Id is #{@post.id} was successfully updated."
      else
        format.js
        @post.errors.each do |key, value|
        end
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
      format.js   { render layout: false}
    end
  end

  def add_favorite
    post = Post.find(params[:post_id])
    post.interactions.each do |itr|
      like = itr.like + 1
      post.interactions.update(like: like)
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def number_to_currency price
    sprintf("$%0.02f", price)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user] = user
  end

  def log_out
    session.delete :user
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_form.html.slim
= form_for(post) do |f|
  - if post.errors.any?
    #error_explanation
      h2
        = pluralize(post.errors.count, "error")
        |  prohibited this post from being saved:
      ul
        - post.errors.full_messages.each do |message|
          li
            = message
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :content
    = f.text_area :content, size:'70x5'
  .actions
    = f.submit

app/views/posts/_post.html.slim
- post.interactions.each do |itr|
  | <tr class=post_
  = post.id
  | >
  td
    = post.id
  td.title
    = post.title
  td.content
    = post.content
  td.cnt-like
    = itr.like
  td
    = link_to budgets_path(:post_id => post.id)
      = button_tag "Download"
  td
    = link_to 'Show', post
  td
    = link_to 'Edit', edit_post_path(post), class: "update-post", remote: true
  td
    = link_to 'Delete', post, method: 'delete', data: {confirm:'Are you sure?'}, remote: true, class: 'destroy-post'
  | </tr>

app/views/posts/_update.html.slim
= form_for(@post,  html: { class: "form-horizontal", role: "form" }, remote: true) do |f|
  - if @post.errors.any?
    #error_explanation
      ul
        - @post.errors.full_messages.each do |message|
          li
            = message
  .form-group
    = f.label :title, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :title, class: "form-control"
  .form-group
    = f.label :content, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_area :content, class: "form-control", row: '6'
  .form-group
    .col-sm-offset-2.col-sm-10.actions
      = f.submit class: "btn btn-primary"

app/views/posts/create.js.erb
$("#error").empty();

<% if @post.errors.empty? %>
  //add new record to table
  $("<%= escape_javascript(render @post) %>").appendTo("#posts");
  //add message success
  <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <% message =  name.to_s == 'notice' ? 'success' : 'danger' %>
      $("ul.notice").html('<div class="alert alert-dismissible alert-<%= message %>"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><%= content_tag :div, msg, :id => "flash_#{name}" %></div>');
    <% end %>
  <% end %>
<% else %>
  console.log('<%= @post.errors.full_messages %>');
  //display new validation messages
  <% @post.errors.full_messages.each do |message| %>
    $("ul#error").append('<li><%= escape_javascript(message)%></li>');
  <% end %>
<% end %>

<%# @post.errors.full_messages.each do |message| %>
//  $("ul#error").append('<li><%#= escape_javascript(message)%></li>');
<%# end %>

app/views/posts/destroy.js.slim
| $('.destroy-post').bind('ajax:success', function () { $(this).closest('tr').fadeOut(); });

app/views/posts/edit.html.slim
h1
  | Editing Post
= render 'form', post: @post
= link_to 'Show', @post
|  | 
= link_to 'Back', posts_path

app/views/posts/index.html.slim
- content_for :title do
  |  List Posts

= render 'partials/messages'
ul.notice
h1
  | Posts
table.table.table-striped.table-bordered.table-hover
  thead
    tr
      th
        | Id post
      th
        | Title
      th
        | Content
      th
        | Like
      th
        | Download
      th[colspan="3"]
  tbody#posts
    = render @posts
br
#form-post-create.col-sm-8.col-sm-offset-2
  = form_for(@post,  html: { class: "form-horizontal", role: "form" }, remote: true) do |f|
    #error_explanation
      ul#error
    .form-group
      = f.label :title, class: "col-sm-2 control-label"
      .col-sm-10
        = f.text_field :title, class: "form-control"
    .form-group
      = f.label :content, class: "col-sm-2 control-label"
      .col-sm-10
        = f.text_area :content, class: "form-control", row: '6'
    .form-group
      .col-sm-offset-2.col-sm-10.actions
        = f.submit class: "btn btn-primary"

div
  = link_to 'javascripts:;', class: 'add-category btn btn-primary', style: 'display: none;' do
    span.glyphicon.glyphicon-plus
    |  New Category

#form-post-update.col-sm-8.col-sm-offset-2

app/views/posts/new.html.slim
h1
  | New Post
= render 'form', post: @post
= link_to 'Back', posts_path

app/views/posts/show.html.slim
p#notice
  = notice
p
  strong
    | Title:
  = @post.title
p
  strong
    | Content:
  = @post.content
= link_to 'Edit', edit_post_path(@post)
|  | 
= link_to 'Back', posts_path

app/views/posts/update.js.slim
| $("#form-post-update").html("
= j render 'posts/update'
| ");


/ | $('#posts').find('#post_
/ = @post.id
/ | ', function(){ $(this).find('td.title').html("
/ = @post.title
/ | "); $(this).find('td.content').html("
/ = @post.content
/ | "); });

/ - if @post.errors.empty?
  //add new record to table
  | $("
  = escape_javascript(render @post)
  | ").appendTo("#posts");

  - flash.each do |name, msg|
    - if msg.is_a?(String)
      - message =  name.to_s == 'notice' ? 'success' : 'danger'
      | $("ul.notice").html('<div class="alert alert-dismissible alert-<%= message %>"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><%= content_tag :div, msg, :id => "flash_#{name}" %></div>');
/ - else
  //display new validation messages
  - @post.errors.full_messages.each do |message|
    | $("ul#error").append('<li><%= escape_javascript(message)%></li>');