config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      sessions: 'authentication/sessions'
  }

  get 'rooms/show'

  scope "(:locale)", locale: /en|vi/ do
    resources :people
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :line_items
    resources :carts, except: [:index, :edit]
    resources :products
    resources :posts
    resources :users
    resources :categories, only: [:index, :show]

    namespace :manager do
      resources :categories
    end
    get 'display' => 'home#post_display'
    post 'add_fav' => 'posts#add_favorite'
    #checkout cart
    get 'checkout' => 'checkouts#checkout'
    post 'confirm' => 'checkouts#confirm'
    #signin & sign up
    controller :sessions do
      get 'login' => :index
      post 'login' => :create
      delete 'logout' => :destroy
    end

    root "home#index"
  end
  resources :comments, only: [:create, :index, :destroy]

  get 'budgets' => 'budgets#download'
  mount ActionCable.server => '/cable'

  get 'room' => 'rooms#show'
  # get '*path', to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, :dependent => :destroy

  def add_product product_id
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(:product_id => product_id)
    end
    current_item
  end
  def total_price
    line_items.to_a.sum { |item| item.total_price}
  end
end

app/models/category.rb
class Category < ApplicationRecord
  self.primary_key = 'cat_id'
  has_many :products, :dependent => :destroy

  validates :cat_id, :cat_name, :cat_content, :presence => true
  validates :cat_name, :cat_id,  :uniqueness => true

  def self.get_category
    select('cat_id, cat_name, cat_content').order('cat_name asc')
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :body, presence: true, allow_blank: false
end

app/models/interaction.rb
class Interaction < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total_price
    product.price * quantity
  end
end

app/models/message.rb
class Message < ApplicationRecord
  after_create_commit { BroadcastMessageJob.perform_later self }
  belongs_to :user
end

app/models/person.rb
class Person < ApplicationRecord

  belongs_to :user, foreign_key: :user_id
  def address
    Address.new(city, state)
  end

  def address=(address)
    self[:city] = address.city
    self[:state] = address.state
    @address = address
  end
end
class Address
  attr_reader :city, :state

  def initialize(city, state)
    @city, @state = city, state
  end

  def ==(other_address)
    city == other_address.city && state == other_address.state
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :interactions, :dependent => :destroy
  has_many :users, through: :interactions
  has_many :comments, dependent: :destroy

  validates :title, :uniqueness => true
  validates :title, :content, :presence => true
end

app/models/product.rb
class Product < ApplicationRecord
  # self.default_scope :order => 'title'

  has_many :line_items
  belongs_to :category, foreign_key: :category_id
  before_destroy :line_item_referencing_product
  mount_uploader :image_url, ImageUploader

  private
    def line_item_referencing_product
      if line_items.empty?
        true
      else
        errors.add(:base, 'line items present')
        false
      end
    end

end

app/models/supports/product.rb
class Supports::Product
  attr_reader :product

  def initialize product
    @product = product
  end

  def category
    @category ||= @product.category
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default authentication modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :person, dependent: :destroy
  has_many :interactions, :dependent => :destroy
  has_many :posts, through: :interactions
  has_many :comments, dependent: :destroy

  # validates :name, :presence => true, :uniqueness => true
  # validates :password, :confirmation => true
  # validate :password_must_be_present
  #
  # attr_accessor :password_confirmation
  # attr_reader   :password

  # def User.encrypt_password(password, salt)
  #   Digest::SHA2.hexdigest(password + "wibble" + salt)
  # end
  #
  # def password=(password)
  #   @password = password
  #
  #   if password.present?
  #     generate_salt
  #     self.hashed_password = self.class.encrypt_password(password, salt)
  #   end
  # end
  #
  # def User.authenticate(name, password)
  #   if user = find_by_name(name)
  #     if user.hashed_password == encrypt_password(password,user.salt)
  #       user
  #     end
  #   end
  # end
  #
  # private
  #   def password_must_be_present
  #     errors.add(:password, "missing password") unless hashed_password.present?
  #   end
  #
  #   def generate_salt
  #     self.salt = self.object_id.to_s + rand.to_s
  #   end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_locale, :authorize
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    #use for query object
    @products = ProductQuery.new(sort_query_params).all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @supports = Supports::Product.new @product
  end

  # GET /products/new
  def new
    @categories = Category.get_category
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    @categories = Category.get_category
    @supports = Supports::Product.new @product
  end

  # POST /products
  # POST /products.json
  def create
    @product = ProductForm.new(product_params)
    @categories = Category.get_category
    if @product.insert(product_params)
      redirect_to products_url
      flash[:notice]='Product was successfully created.'
    else
      render :new
      render json: @product.errors, status: :unpocessably_entity
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to products_url, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price, :category_id)
    end

    #use for query object
    def sort_query_params
      { sort: :by_title, type: :desc }
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def number_to_currency price
    sprintf("$%0.02f", price)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user] = user
  end

  def log_out
    session.delete :user
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_form.html.slim
.container-fluid
  .col-sm-12.col-offset-2
    = form_for(product, html: { class: "form-horizontal", role: "form" } ) do |f|
      - if product.errors.any?
        #error_explanation
          ul
            - product.errors.full_messages.each do |message|
              li
                = message
      .form-group
        = f.label :cat_name, class: "col-sm-2 control-label"
        .col-sm-10
          - if product.category_id.nil?
            = f.select :category_id, :class => "form-control" do
              - @categories.each do |categori|
                = content_tag(:option, categori.cat_name, value: categori.cat_id)
          - else
            = @supports.category.cat_name
      .form-group
        = f.label :title, class: "col-sm-2 control-label"
        .col-sm-10
          = f.text_field :title, class: "form-control"
      .form-group
        = f.label :description, class: "col-sm-2 control-label"
        .col-sm-10
          = f.text_area :description, class: "form-control"
      .form-group
        = f.label :image_url, class: "col-sm-2 control-label"
        .col-sm-10
          = f.file_field :image_url, class: "form-control"
      .form-group
        = f.label :price, class: "col-sm-2 control-label"
        .col-sm-10
          = f.text_field :price, class: "form-control"
      .form-group
        .col-sm-offset-2.col-sm-10.actions
          = f.submit class: "btn btn-primary"

app/views/products/_product.html.slim
tr
  td
    = product.title
  td
    = product.description
  td
    / = image_tag(product.image_url)
    = link_to(image_tag(product.image_url.small_thumb.url, alt: 'Image'), product.image_url.url, target: '_blank') if product.image_url?
  td
    = product.price
  td
    = link_to 'Show', product
  td
    = link_to 'Edit', edit_product_path(product)
  td
    = link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }

app/views/products/edit.html.slim
- content_for :title do
  |  Add product

.page-header
  h1
    | Editing Product

= render 'form', product: @product

= link_to @product, class: 'btn btn-default' do
  span.glyphicon.glyphicon-list-alt
  |  Show

= link_to products_path, class: 'btn btn-default' do
  span.glyphicon.glyphicon-list-alt
  |  Back

app/views/products/index.html.slim
- content_for :title do
  |  List Product

= render 'partials/messages'
.page-header
  = link_to new_product_path, class: 'add-category btn btn-primary' do
    span.glyphicon.glyphicon-plus
    |  New Product
  h1
    | Products
br
table.table.table-striped.table-bordered.table-hover
  thead
    tr
      th
        | Title
        span.glyphicon.glyphicon-sort.icon_sort
      th
        | Description
        span.glyphicon.glyphicon-sort.icon_sort
      th
        | Image url
        span.glyphicon.glyphicon-sort.icon_sort
      th
        | Price
        span.glyphicon.glyphicon-sort.icon_sort
      th[colspan="3"]
  tbody
    = render @products

app/views/products/new.html.slim
- content_for :title do
  |  Add product

= render 'partials/messages'
.page-header
  h1
    | New Product
= render 'form', product: @product
= link_to products_path, class: 'btn btn-default' do
  span.glyphicon.glyphicon-list-alt
  |  Back 

app/views/products/show.html.slim
p#notice
  = notice
p
  strong
    | Title:
  = @product.title
p
  strong
    | Description:
  = @product.description
p
  strong
    | Image:
  = link_to(image_tag(@product.image_url.medium_thumb.url, alt: 'Image'), @product.image_url.url, target: '_blank') if @product.image_url?
p
  strong
    | Price:
  = @product.price
= button_to 'Add to cart', line_items_path(:product_id => @product), class: 'btn btn-default', remote: true
= link_to 'Back to home', root_path, class: 'btn btn-default'