config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      sessions: 'authentication/sessions'
  }

  get 'rooms/show'

  scope "(:locale)", locale: /en|vi/ do
    resources :people
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :line_items
    resources :carts, except: [:index, :edit]
    resources :products
    resources :posts
    resources :users
    resources :categories, only: [:index, :show]

    namespace :manager do
      resources :categories
    end
    get 'display' => 'home#post_display'
    post 'add_fav' => 'posts#add_favorite'
    #checkout cart
    get 'checkout' => 'checkouts#checkout'
    post 'confirm' => 'checkouts#confirm'
    #signin & sign up
    controller :sessions do
      get 'login' => :index
      post 'login' => :create
      delete 'logout' => :destroy
    end

    root "home#index"
  end
  resources :comments, only: [:create, :index, :destroy]

  get 'budgets' => 'budgets#download'
  mount ActionCable.server => '/cable'

  get 'room' => 'rooms#show'
  # get '*path', to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, :dependent => :destroy

  def add_product product_id
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(:product_id => product_id)
    end
    current_item
  end
  def total_price
    line_items.to_a.sum { |item| item.total_price}
  end
end

app/models/category.rb
class Category < ApplicationRecord
  self.primary_key = 'cat_id'
  has_many :products, :dependent => :destroy

  validates :cat_id, :cat_name, :cat_content, :presence => true
  validates :cat_name, :cat_id,  :uniqueness => true

  def self.get_category
    select('cat_id, cat_name, cat_content').order('cat_name asc')
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :body, presence: true, allow_blank: false
end

app/models/interaction.rb
class Interaction < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total_price
    product.price * quantity
  end
end

app/models/message.rb
class Message < ApplicationRecord
  after_create_commit { BroadcastMessageJob.perform_later self }
  belongs_to :user
end

app/models/person.rb
class Person < ApplicationRecord

  belongs_to :user, foreign_key: :user_id
  def address
    Address.new(city, state)
  end

  def address=(address)
    self[:city] = address.city
    self[:state] = address.state
    @address = address
  end
end
class Address
  attr_reader :city, :state

  def initialize(city, state)
    @city, @state = city, state
  end

  def ==(other_address)
    city == other_address.city && state == other_address.state
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :interactions, :dependent => :destroy
  has_many :users, through: :interactions
  has_many :comments, dependent: :destroy

  validates :title, :uniqueness => true
  validates :title, :content, :presence => true
end

app/models/product.rb
class Product < ApplicationRecord
  # self.default_scope :order => 'title'

  has_many :line_items
  belongs_to :category, foreign_key: :category_id
  before_destroy :line_item_referencing_product
  mount_uploader :image_url, ImageUploader

  private
    def line_item_referencing_product
      if line_items.empty?
        true
      else
        errors.add(:base, 'line items present')
        false
      end
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default authentication modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :person, dependent: :destroy
  has_many :interactions, :dependent => :destroy
  has_many :posts, through: :interactions
  has_many :comments, dependent: :destroy

  # validates :name, :presence => true, :uniqueness => true
  # validates :password, :confirmation => true
  # validate :password_must_be_present
  #
  # attr_accessor :password_confirmation
  # attr_reader   :password

  # def User.encrypt_password(password, salt)
  #   Digest::SHA2.hexdigest(password + "wibble" + salt)
  # end
  #
  # def password=(password)
  #   @password = password
  #
  #   if password.present?
  #     generate_salt
  #     self.hashed_password = self.class.encrypt_password(password, salt)
  #   end
  # end
  #
  # def User.authenticate(name, password)
  #   if user = find_by_name(name)
  #     if user.hashed_password == encrypt_password(password,user.salt)
  #       user
  #     end
  #   end
  # end
  #
  # private
  #   def password_must_be_present
  #     errors.add(:password, "missing password") unless hashed_password.present?
  #   end
  #
  #   def generate_salt
  #     self.salt = self.object_id.to_s + rand.to_s
  #   end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    @cart = current_cart
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product.id)

    respond_to do |format|
      if @line_item.save
        format.js
        format.html { redirect_to @line_item.cart, notice: 'Your cart was successfully created.' }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.js
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.js   { render layout: false}
      format.html { redirect_to line_items_url, notice: 'Line item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      # begin
        @line_item = LineItem.find(params[:id])
      # rescue ActiveRecord::RecordNotFound
      #   flash[:error] = "error"
      # end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:product_id, :cart_id)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def number_to_currency price
    sprintf("$%0.02f", price)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user] = user
  end

  def log_out
    session.delete :user
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/line_items/_form.html.slim
= form_for(line_item) do |f|
  - if line_item.errors.any?
    #error_explanation
      h2
        = pluralize(line_item.errors.count, "error")
        |  prohibited this line_item from being saved:
      ul
        - line_item.errors.full_messages.each do |message|
          li
            = message
  .field
    = f.label :product_id
    = f.number_field :product_id
  .field
    = f.label :cart_id
    = f.number_field :cart_id
  .actions
    = f.submit

app/views/line_items/_line_item.html.slim
tr
  td
  td
    = line_item.product.title
  td
    = line_item.quantity
  td
    = line_item.product.price
  td
    = number_to_currency(line_item.total_price)
  td
    = link_to 'Delete item', line_item_path(line_item.id), method: :delete, data: {confirm: 'Are you sure?'}, class: 'destroy-item', remote: true

app/views/line_items/destroy.js.erb
$('.destroy-item').bind('ajax:success', function () {
    $(this).closest('tr').fadeOut();
    console.log('test');
});

app/views/line_items/edit.html.slim
h1
  | Editing Line Item
= render 'form', line_item: @line_item
= link_to 'Show', @line_item
|  | 
= link_to 'Back', line_items_path

app/views/line_items/index.html.slim
p#notice
  = notice
h1
  | Line Items
table
  thead
    tr
      th
        | Product
      th
        | Cart
      th[colspan="3"]
  tbody
    - @line_items.each do |line_item|
      tr
        td
          = line_item.product_id
        td
          = line_item.cart_id
        td
          = link_to 'Show', line_item
        td
          = link_to 'Edit', edit_line_item_path(line_item)
        td
          = link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New Line Item', new_line_item_path

app/views/line_items/new.html.slim
h1
  | New Line Item
= render 'form', line_item: @line_item
= link_to 'Back', line_items_path

app/views/line_items/show.html.slim
p#notice
  = notice
p
  strong
    | Product:
  = @line_item.product_id
p
  strong
    | Cart:
  = @line_item.cart_id
= link_to 'Edit', edit_line_item_path(@line_item)
|  | 
= link_to 'Back', line_items_path